### ISSUE TITLE
Store inviter for invited user

### ISSUE THREAD

**Issue by Prince213** [ShanghaitechGeekPie/coursebench-backend#15]
This might not be necessary if it's acceptable to look up inviter by its invitation code.

**Comment by Prince213** [comment]
Closed. Consensus is that logic involving this would be done in registration.

**Comment by AstatineAi** [comment]
This is relied on by #8 

### Database
- Add field `inviter` for user


### Business Logic

- When registering with valid invitation code, add the corresponding inviter for the new user.
