### ISSUE TITLE
[BUG] Crash on `/comment/recent`

### ISSUE THREAD

**Issue by WAAutoMaton** [ShanghaitechGeekPie/coursebench-backend#19]
![image](https://github.com/ShanghaitechGeekPie/coursebench-backend/assets/24771667/5ca5e4c8-b663-4afb-acde-529093a03abb)
![image](https://github.com/ShanghaitechGeekPie/coursebench-backend/assets/24771667/f358290f-c62b-48f6-b5d7-c191043a7ea0)

**Comment by Tanngent2005** [comment]
make a PR
